version: "3.9"  
services:
  db:
    image: mariadb:10.6
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=tg123 # Default password 
    command: mysqld --lower_case_table_names=1 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306" # Export port for development, you can remove it as needed.
    volumes:
      - type: volume
        source: tg-driver-db-data
        target: /var/lib/mysql


  # Backend image is publish to docker hub
  # https://hub.docker.com/r/kentchiu/tg-driver-api
  # Change the image to to upgrade to new version
  backend:
    restart: always
    image: kentchiu/tg-driver-api:0.2.0  
    depends_on:
      - db
    ports:
      - "8888:8080" # Restful API export to http://localhost:8888
    links:
      - db
    volumes:
      - type: volume
        source: tg-driver-data
        target: /tg-driver

  # Frontend image is publish to docker hub
  # https://hub.docker.com/r/kentchiu/tg-drvier-web
  # Change the image to to upgrade to new version
  frontend:
    restart: always
    image: kentchiu/tg-driver-web:0.2.0  
    ports:
      - "3333:3000" # Web GUI export to http://localhost:3333



volumes:
  tg-driver-data:
  tg-driver-db-data: